config/routes.rb
Qna::Application.routes.draw do
  
  resources :posts do
    member { post :vote }
    resources :comments
  end
  
  get 'tags/:tag', to: 'posts#index', as: :tag

  resources :users do
      member do
        get :following, :followers
      end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_reputation :votes, source: :user, aggregated_by: :sum
  attr_accessible :content, :tag_list
  acts_as_taggable
  belongs_to :user

  validates :content, presence: true
  validates :user_id, presence: true

#  default_scope order: 'posts.created_at DESC'

  has_many :comments, dependent: :destroy

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy
  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).find_with_reputation(:votes, :all, order: "votes desc")
    else
      @posts = Post.find_with_reputation(:votes, :all, order: "votes desc")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    if current_user.id != @post.user_id
      redirect_to '/posts', notice: "You don't have access to edit this post!"
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
#        flash[:success] = "Post created!"
#        redirect_to @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #Not allowing the other user to delete a post...!! but still it can be updated...!!
  def correct_user
    @post = current_user.posts.find_by_id(params[:id])
    if @post.nil?
      redirect_to '/posts', notice: 'Sorry you cannot delete this post!'
    else
      redirect_to '/posts', notice: 'The post has been deleted!'
    end
  end
  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @post = Post.find(params[:id])
    @post.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>
  
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>QUESTS...</h1>
<div class="btn btn-large btn-block"><%= link_to 'New Post', new_post_path %></div>
</br>
</br>
<h3> SELECT YOUR CATEGORY OF INTEREST.... </h3>
</br>

<div id="tag_cloud">
  <% tag_cloud Post.tag_counts, %w[s m l] do |tag, css_class| %>
    <div class="btn btn-inverse"><%= link_to tag.name.upcase, tag_path(tag.name), class: css_class %></div>
  <% end %>
</div>
<hr>
</br>
<div id="posts">
 <% @posts.each do |post| %>
  
  <h3><%= post.user.name %>:</h3> <p><%=simple_format post.content %></p>
  Tags: <div class="btn"><%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></div>
  
  <div class="btn btn-success"><%= link_to 'See', post %></div>
  <% if current_user.id == post.user_id %>
      <div class="btn btn-warning"><%= link_to 'Edit', edit_post_path(post) %></div>
      <div class="btn btn-danger"><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
  <% end %>
    </br>
     | <%= pluralize post.reputation_value_for(:votes).to_i, "vote" %>
     <% if current_user && !current_user.voted_for?(post) %>
       | <%= link_to "up", vote_post_path(post, type: "up"), method: "post" %>
       | <%= link_to "down", vote_post_path(post, type: "down"), method: "post" %>
     </br>
     <% end %>
    </br>
    <hr>
 
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h3>QUESTION</h3>
</br>
<p id="notice"><%= notice %></p>

<p>
  <h3><%= @post.user.name %>:</h3>
</p>

<p>
  <b>Ques:</b>
  <%= @post.content %>
</p>
</br>
<p>
<h3>Answers</h3>
<hr>
</p>
<% @post.comments.each do |comment| %>
  <p>
    <b>By:</b>
    <% user=User.find(comment.commenter) %>
    <%= user.name %>
  </p>
 
  <p>
    <b>Ans:</b>
    <%= comment.body %>
  </p>

  <p>
    <% if current_user.id == user.id %>
      <%= link_to 'Delete', post_comment_path(@post,comment), confirm: 'Are you sure?', method: :delete %>
    <% end %>
  </p>
  <hr>
<% end %>


<h3>Add an Answer:</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  
  
  <div class="field">
   
    <%= f.text_area :body, :rows => "8" %>
  </div>
  <div class="action">
    <%= f.submit %>
  </div>
<% end %>

<br />

<div class="btn"><%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %></div>